spring:
  elastic:
    job:
      zookeeper:
        serverLists: localhost:2181
        namespace: test-job
      config:
        simpleJob:
          -
            name: test
            cron: 0/5 * * * * ?
            shardingTotalCount: 3
            jobClass: org.xc.elasticjob.MyJob
            overwrite: true
            listeners:
              - org.xc.elasticjob.listener.MyListener
              - org.xc.elasticjob.listener.MyListener
        dataFlowJob:
          - name: dataflowtest
            cron: 0/5 * * * * ?
            shardingTotalCount: 1
            jobClass: org.xc.elasticjob.MyDataFlowJob
            overwrite: true
            streamingProcess: true
            disabled: true
        scriptJob:
          - name: scripttest
            cron: 0/1 * * * * ?
            shardingTotalCount: 1
            overwrite: true
            scriptCommandLine: C:/Users/THTF/Desktop/test.bat
            disabled: true